
import React, { useState, useEffect } from "react";

export default function Card() {
  const [state, setState] = useState(
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBw0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ8NDQ0NFREWFhURFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDQ0NDg0NDysZFRktKy0rLS0rNys3KystKysrLS03KysrLSs3LSsrKy03LTctLS0tKy0rKysrKy0rNysrK//AABEIAMoA+gMBIgACEQEDEQH/xAAXAAEBAQEAAAAAAAAAAAAAAAAAAQIE/8QAGhABAQEAAwEAAAAAAAAAAAAAABEBcZGhIf/EABcBAQEBAQAAAAAAAAAAAAAAAAABBwb/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDvEV2DLVAEURQFQEUAFEVEAAFQBRAFAQBBQAAEBQBQEAABWAFVVQQVUBFABRARRFQFQEUSgqiAiiAKIAAKolVAVAABBQAGFQxVVUXAURUQVAFEUAARRAFEUAQBRAAAAAUEAVAABNAqoCsKiqqiKIoigKgCiKiAAKIAogCiAKCAAAqAACKKgCggAUQEAFURQURRAwAUQBpExQAAFQBRAFEAVAAEAUQABAAABAUAFABFAoC3EAUQEUQBVZqgAAAAAAAAIAAAoIAqAAAKgCiiKgAAACKIAogCiALRFAEAUQBRAFQAAAAFUTnxRBAFEEUVRAFAEUSgKAAIAoAAAAAgCCqCAogCoAKgACAoCACKKKgIolAUAFEAUQBRKAogIogCiAqiAKIAqAAIUFQSgogKlVAFEUFEAUAAARRAFEAUQBRAFEAUQoKgAUAUEAAQAAUEAUAAAFEBFABRAFEL9gKCUFEAUQBUAFQABAABVBAFEKAICqIoCoCKIAoXsAABRARRAVaIAUAAAAQBRAAADdBBQAEVFFAwEFRcAAEA0AAAVMAURQEAAAAAAAAAEF00VAAAQH//2Q=="
  );
  useEffect(() => {
    console.log("mount phase");

    return (() => {
      alert("unmount");
    });
  }, [state]);  

  return (
    <div>
      <img src={state} alt="card-img" width={200} />

      <button
        onClick={() =>
          setState("https://www.w3schools.com/howto/img_avatar.png")
        }
      >
        Change Image
      </button>
    </div>
  );
}
